### ISSUE TITLE
Use inter-ontology relations to link manual annotations 

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/gocamgen#33]
The basic idea here is that when a relationship exists between terms in the ontology, e.g. MF part_of BP, then if there are manual annotations to both (and either no extensions or extensions are all the same), then those annotations could be connected during the import.

We need some illustrative examples here, so holding off on adding this to the to-do list just yet.

**Comment by ukemi** [comment]
For example from these lines in the GPAD file:

MGI | MGI:95522 | enables | GO:0005007 | MGI:MGI:79015\|PMID:2161540 | ECO:0000314 |   | 20091002 | MGI
-- | -- | -- | -- | -- | -- | -- | -- | --

MGI | MGI:95522 | acts_upstream_of_or_within | GO:0008543 | MGI:MGI:79015\|PMID:2161540 | ECO:0000316 | UniProtKB:P09038 | 20160510 | MGI
-- | -- | -- | -- | -- | -- | -- | -- | --

MGI | MGI:95522 | enables | GO:0017134 | MGI:MGI:79015\|PMID:2161540 | ECO:0000314 |   |   | 20160512 | MGI
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

We would get the construct at the far left of the model:gomodel:bfa1a7ae-0c5e-418b-a172-e5d1773414f2  because fibroblast growth factor-activated receptor activity is part_of fibroblast growth factor receptor signaling pathway and has_part some fibroblast growth factor binding. The last relation between functions would have no evidence at this point in time.
